# -*- coding: utf-8 -*-
"""ML Practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFmRNLXVPY5qqFxwNYf2akwWgPz02X2Q
"""

import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso,Ridge
from sklearn.metrics import r2_score

df = pd.read_csv('dataset.csv')
df = df.replace('?',np.nan)

df = df.apply(pd.to_numeric, errors='ignore')

X = df.drop('feature_25',axis=1)
Y = df['feature_25'].values

num_cols = X.select_dtypes(include=["int","float"]).columns.tolist()
cat_cols = X.select_dtypes(include=["category","object","bool"]).columns.tolist()

num_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='mean',missing_values=np.nan)),
    ('scaler',StandardScaler())
])

col_transformer = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent',missing_values=np.nan)),
    ('onehot',OneHotEncoder())
])

preprocessor = ColumnTransformer(transformers=[
    ('num_transform',num_transformer,num_cols),
    ('cat_transform',col_transformer,cat_cols)
],remainder='passthrough')

preprocessor_pipeline = Pipeline(steps=[
    ('preprocess',preprocessor)
])

X_preprocessed = preprocessor_pipeline.fit_transform(X)

imputer_y = SimpleImputer(strategy='mean',missing_values=np.nan)
sc_y = StandardScaler()
Y = imputer_y.fit_transform(Y.reshape(-1,1)).flatten()
Y = sc_y.fit_transform(Y.reshape(-1,1)).flatten()

X_train,X_test,Y_train,Y_test = train_test_split(X_preprocessed,Y,test_size=0.2,random_state=42)

model = Ridge(alpha=0.5)
model.fit(X_train,Y_train)

Y_pred = model.predict(X_test)

model_r2_score = r2_score(Y_test,Y_pred)

model_r2_score
